//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/_Scripts/Inputs Maps/InputsDM.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputsMaps
{
    public partial class @InputsDM : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputsDM()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputsDM"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""eb7f45de-ee3b-4191-ae67-82356ea43618"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8aea4457-75f4-4ba8-ae6e-cc4be2644690"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""031bc89a-4447-4bd6-8358-6d051e492cc8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3360c3e9-c57e-4135-9634-386c5876f00b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCW"",
                    ""type"": ""Button"",
                    ""id"": ""ab5d66ea-0f0a-4fa1-911f-913d86a92f66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateACW"",
                    ""type"": ""Button"",
                    ""id"": ""992a5758-4b99-4fc8-bfea-d039da944de8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamCW"",
                    ""type"": ""Button"",
                    ""id"": ""4953df66-372a-4ff7-a523-79a31c99add3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamACW"",
                    ""type"": ""Button"",
                    ""id"": ""73490d8e-b4b2-44e3-9fab-a8d41a716965"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VerticalAngle"",
                    ""type"": ""Value"",
                    ""id"": ""e3511339-424c-47b1-90de-fc247aaf6631"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2e551e2a-c581-44f2-8c11-a90b331c7561"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07fbfb64-a6f6-4cae-a31b-247f784cda01"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""355f05be-f6dd-4360-95c3-a1e376e4979a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateACW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b8d45e9-e0f2-41b5-8bf6-18901a91e7f4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamCW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d4c0f15-f9d7-4a83-b924-563c9c2b0b5d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamACW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ba1d60d-7c5c-46ee-9b7c-045cca40b7bf"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""5e8423a3-b902-4d4a-8768-0cb649077338"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""56dbeb85-27c3-4426-b81e-738d18e27b60"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MK"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a26a5a7a-65c5-4d24-a91f-9b1421af30e8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MK"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""57340c1a-a783-4b4c-834d-825a783eae53"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MK"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""88ceff37-ea55-4225-bb1d-71103529fbc3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MK"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0fe5d1c2-2a68-4b83-8919-dbef3c5fceb9"",
                    ""path"": ""<VirtualMouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MK"",
            ""bindingGroup"": ""MK"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
            m_Gameplay_Mouse = m_Gameplay.FindAction("Mouse", throwIfNotFound: true);
            m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
            m_Gameplay_RotateCW = m_Gameplay.FindAction("RotateCW", throwIfNotFound: true);
            m_Gameplay_RotateACW = m_Gameplay.FindAction("RotateACW", throwIfNotFound: true);
            m_Gameplay_RotateCamCW = m_Gameplay.FindAction("RotateCamCW", throwIfNotFound: true);
            m_Gameplay_RotateCamACW = m_Gameplay.FindAction("RotateCamACW", throwIfNotFound: true);
            m_Gameplay_VerticalAngle = m_Gameplay.FindAction("VerticalAngle", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private IGameplayActions m_GameplayActionsCallbackInterface;
        private readonly InputAction m_Gameplay_Move;
        private readonly InputAction m_Gameplay_Mouse;
        private readonly InputAction m_Gameplay_Interact;
        private readonly InputAction m_Gameplay_RotateCW;
        private readonly InputAction m_Gameplay_RotateACW;
        private readonly InputAction m_Gameplay_RotateCamCW;
        private readonly InputAction m_Gameplay_RotateCamACW;
        private readonly InputAction m_Gameplay_VerticalAngle;
        public struct GameplayActions
        {
            private @InputsDM m_Wrapper;
            public GameplayActions(@InputsDM wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Gameplay_Move;
            public InputAction @Mouse => m_Wrapper.m_Gameplay_Mouse;
            public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
            public InputAction @RotateCW => m_Wrapper.m_Gameplay_RotateCW;
            public InputAction @RotateACW => m_Wrapper.m_Gameplay_RotateACW;
            public InputAction @RotateCamCW => m_Wrapper.m_Gameplay_RotateCamCW;
            public InputAction @RotateCamACW => m_Wrapper.m_Gameplay_RotateCamACW;
            public InputAction @VerticalAngle => m_Wrapper.m_Gameplay_VerticalAngle;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                    @Mouse.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse;
                    @Mouse.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse;
                    @Mouse.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMouse;
                    @Interact.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                    @RotateCW.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCW;
                    @RotateCW.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCW;
                    @RotateCW.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCW;
                    @RotateACW.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateACW;
                    @RotateACW.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateACW;
                    @RotateACW.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateACW;
                    @RotateCamCW.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamCW;
                    @RotateCamCW.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamCW;
                    @RotateCamCW.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamCW;
                    @RotateCamACW.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamACW;
                    @RotateCamACW.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamACW;
                    @RotateCamACW.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotateCamACW;
                    @VerticalAngle.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnVerticalAngle;
                    @VerticalAngle.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnVerticalAngle;
                    @VerticalAngle.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnVerticalAngle;
                }
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Mouse.started += instance.OnMouse;
                    @Mouse.performed += instance.OnMouse;
                    @Mouse.canceled += instance.OnMouse;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @RotateCW.started += instance.OnRotateCW;
                    @RotateCW.performed += instance.OnRotateCW;
                    @RotateCW.canceled += instance.OnRotateCW;
                    @RotateACW.started += instance.OnRotateACW;
                    @RotateACW.performed += instance.OnRotateACW;
                    @RotateACW.canceled += instance.OnRotateACW;
                    @RotateCamCW.started += instance.OnRotateCamCW;
                    @RotateCamCW.performed += instance.OnRotateCamCW;
                    @RotateCamCW.canceled += instance.OnRotateCamCW;
                    @RotateCamACW.started += instance.OnRotateCamACW;
                    @RotateCamACW.performed += instance.OnRotateCamACW;
                    @RotateCamACW.canceled += instance.OnRotateCamACW;
                    @VerticalAngle.started += instance.OnVerticalAngle;
                    @VerticalAngle.performed += instance.OnVerticalAngle;
                    @VerticalAngle.canceled += instance.OnVerticalAngle;
                }
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);
        private int m_MKSchemeIndex = -1;
        public InputControlScheme MKScheme
        {
            get
            {
                if (m_MKSchemeIndex == -1) m_MKSchemeIndex = asset.FindControlSchemeIndex("MK");
                return asset.controlSchemes[m_MKSchemeIndex];
            }
        }
        public interface IGameplayActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnMouse(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnRotateCW(InputAction.CallbackContext context);
            void OnRotateACW(InputAction.CallbackContext context);
            void OnRotateCamCW(InputAction.CallbackContext context);
            void OnRotateCamACW(InputAction.CallbackContext context);
            void OnVerticalAngle(InputAction.CallbackContext context);
        }
    }
}
